### ISSUE TITLE
Improve change requests capabilities

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#297]
Change Requests is a very important concept in order to make registries more dynamic. 
Right now OpenSPP change request only allow to do changes in the context of a group. 
We need to add new capabilities:
- [ ] Create a change requests as an individual #294 
- [ ] Capability to create a group or an individual (independent of a group)
- [ ] Request for program enrollment

Before starting to implement, please propose a way to do.

**Comment by dasunhegoda** [comment]
Discussion points from the meeting with @gonzalesedwin1123 

- Two types of individual change requests are recognized:
-- Request made by the individual themselves.
-- Request made on behalf of another individual.
- Different artifacts are required depending on the type of request (e.g., address or name change). Identification must be provided for each change request (CR).
- The validation process may vary according to the type of CR.

- The plan is to adapt the existing module with necessary modifications for handling these requests.

@jeremi Question: Is a validation flow necessary during updates from the CRVS since the CRVS is considered a single source of truth?

cc: @reichie020212

**Comment by dasunhegoda** [comment]
The will accommodate CRs at the individual level too.

**Comment by dasunhegoda** [comment]
The base module will always have a validation flow.
